# Generated by Django 4.2.4 on 2023-08-31 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0002_alter_apikey_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='usage_rate',
            field=models.CharField(default='5/minute', max_length=55),
        ),
    ]
