# Generated by Django 4.2.4 on 2023-08-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0003_apikey_usage_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='usage_rate',
            field=models.CharField(blank=True, default='5/minute', max_length=55),
        ),
    ]
