# Generated by Django 4.2.4 on 2023-09-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0006_rename_throttle_rate_apikey_usage_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='usage_rate',
        ),
        migrations.AddField(
            model_name='apikey',
            name='roll',
            field=models.CharField(blank=True, default='3/10/second', max_length=55),
        ),
    ]
