# Generated by Django 4.2.4 on 2023-09-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0007_remove_apikey_usage_rate_apikey_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='roll',
            field=models.CharField(blank=True, default='5/1/min', max_length=55),
        ),
    ]
