# Generated by Django 4.2.2 on 2023-08-13 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
